CREATE TABLE IF NOT EXISTS CLIENT(
id       SERIAL PRIMARY KEY,
name     VARCHAR(100) NOT NULL,
lastname VARCHAR(100) NOT NULL,
email    VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
rol      VARCHAR(100) NOT NULL
);